# Generated by Django 4.0.6 on 2022-08-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_marks', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('science_marks', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('english_marks', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('CS_marks', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('total_marks', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_performance.student')),
            ],
        ),
    ]
