# Generated by Django 4.0.6 on 2022-08-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_performance.student'),
        ),
    ]
