# Generated by Django 4.0.6 on 2022-08-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0002_alter_performance_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='id',
        ),
        migrations.AlterField(
            model_name='performance',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_performance.student'),
        ),
    ]
