# Generated by Django 4.0.6 on 2022-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_remove_performance_id_alter_performance_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
