# Generated by Django 4.0.6 on 2022-08-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0004_remove_student_id_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='total_marks',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4),
        ),
    ]
